import React from 'react';
import Breadcrumb from '../../components/Breadcrumb';
import PageHeader from '../../components/PageHeader';
import DocumentCard from '../../components/DocumentCard';
import { Sparkles, FileText, CheckCircle2, Phone, Mail } from 'lucide-react';

export default function AdmissionPage() {
  const requiredDocuments = [
    "2 Passport size photos of a child.",
    "2 Family photo ( parents & the child)",
    "Previous year result",
    "Previous TC ( if seeking admission in class 1 or above)",
    "Date of Birth certificate ( if seeking admission in pre- primary classes)",
    "PEN ( Permanent Education Number) generated by previous school"
  ];

  return (
    <div className="bg-slate-50 min-h-screen pb-16">
      <Breadcrumb items={[{ label: 'Admissions' }]} />
      <PageHeader 
        title="School Admissions 2026-27" 
        subtitle="Sun Flower Public School — Dayalbagh, Agra"
      />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-12 space-y-10">
        {/* Admission Open Announcement Banner */}
        <div className="bg-gradient-to-r from-[#10457B] to-[#1a5b9c] rounded-2xl p-8 text-white shadow-lg flex flex-col md:flex-row items-center justify-between gap-6">
          <div>
            <div className="inline-flex items-center gap-2 bg-[#E9931C] text-white px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider mb-3">
              <Sparkles className="w-4 h-4" /> Latest Notice
            </div>
            <h2 className="text-2xl sm:text-3xl font-extrabold mb-2">
              Admission Open for Session 2026-27
            </h2>
            <p className="text-blue-100 text-base">
              Nursery to Class X | Affiliated to CBSE, New Delhi
            </p>
          </div>
          <div className="flex flex-col sm:flex-row gap-4 w-full md:w-auto">
            <a 
              href="tel:+918899659410" 
              className="bg-[#E9931C] hover:bg-amber-600 text-white font-bold px-6 py-3 rounded-xl transition text-center flex items-center justify-center gap-2 shadow-md"
            >
              <Phone className="w-5 h-5" /> Call +91-8899659410
            </a>
          </div>
        </div>

        {/* Required Documents Card */}
        <div className="bg-white rounded-2xl p-8 shadow-sm border border-slate-100">
          <h2 className="text-2xl font-bold text-[#10457B] mb-6 pb-2 border-b-2 border-[#E9931C] inline-block">
            REQUIRED DOCUMENTS FOR ADMISSION
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {requiredDocuments.map((doc, idx) => (
              <div key={idx} className="flex items-start gap-4 p-4 rounded-xl bg-slate-50 border border-slate-200">
                <div className="w-7 h-7 rounded-full bg-[#10457B] text-white flex items-center justify-center font-bold text-sm flex-shrink-0 mt-0.5">
                  {idx + 1}
                </div>
                <p className="text-slate-800 font-medium text-base leading-relaxed">{doc}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Rules & Fee Structure Documents */}
        <div>
          <h2 className="text-2xl font-bold text-[#10457B] mb-6 pb-2 border-b-2 border-[#E9931C] inline-block">
            FEE STRUCTURE & SCHOOL RULES
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <DocumentCard 
              title="Fee Structure & Fee Rules" 
              docUrl="https://sunfloweragra.com/docs/fee-structure.jpg" 
            />
            <DocumentCard 
              title="School Rules & Student Guidelines" 
              docUrl="https://sunfloweragra.com/docs/rules-and-regulations.pdf" 
            />
          </div>
        </div>

      </div>
    </div>
  );
}
